/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.Color;

import clases.Estacion;
import clases.MateriaPrima;

/**
 *
 * @author joses
 */
public class PantallaPrincipal extends javax.swing.JFrame implements KeyListener {
    Estacion[] estaciones;
    
    MateriaPrima bolita1;
    MateriaPrima bolita2;
    MateriaPrima bolita3;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        this.bolita1 = new MateriaPrima(Color.YELLOW, 275, 300,5);
        this.add(this.bolita1.getBolita());
        
        this.bolita2 = new MateriaPrima(Color.MAGENTA, 250, 300,5);
        this.add(this.bolita2.getBolita());
        
        this.bolita3 = new MateriaPrima(Color.GRAY, 50, 20,5);
        this.add(this.bolita3.getBolita());
        
        this.estaciones = new Estacion[4];
        this.estaciones[0] = new Estacion(Color.BLUE, 40, 50,25);
        this.estaciones[1] = new Estacion(Color.CYAN, 40, 275,30);
        this.estaciones[2] = new Estacion(Color.GREEN, 400, 50,10);
        this.estaciones[3] = new Estacion(Color.RED, 400, 275,5);
        this.add(this.estaciones[0]);
        this.add(this.estaciones[1]);
        this.add(this.estaciones[2]);
        this.add(this.estaciones[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jButton1)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.bolita1.setPosicionX(this.estaciones[0].getX());
        this.bolita1.setPosicionY(this.estaciones[0].getY());
        this.bolita1.start();
        
        this.bolita2.setPosicionX(this.estaciones[2].getX());
        this.bolita2.setPosicionY(this.estaciones[2].getY());
        this.bolita2.start();
        
        this.bolita3.setPosicionX(this.estaciones[3].getX());
        this.bolita3.setPosicionY(this.estaciones[3].getY());
        this.bolita3.start();
        /*
         try {
        
       int initialPositionX = mp.getX();
        for (int i = 0; i < initialPositionX; i++) {
            initialPositionX = initialPositionX - 1;
            mp.setLocation(initialPositionX, mp.getY());
            System.out.println(mp.getX());
            this.repaint();
           
                Thread.sleep(200);
            
        }
            
            } catch (InterruptedException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void keyPressed(KeyEvent e) {
        // Handle the key press event
        System.out.println("Key pressed: " + e.getKeyChar());
    }

    @Override
    public void keyReleased(KeyEvent e) {
        // Handle the key release event
        System.out.println("Key pressed: " + e.getKeyChar());
    }

    @Override
    public void keyTyped(KeyEvent e) {
        // Handle the key typed event
        System.out.println("Key pressed: " + e.getKeyChar());
    }
    
    public void moverLabel() {
        int delay = 1; // Milliseconds between each animation frame
        Timer timer = new Timer(delay, new ActionListener() {
            int step = 2;
            @Override
            public void actionPerformed(ActionEvent e) {
                //int x = mp.getX() + step;
                //int y = mp.getY();

                /*
                if (x > getWidth() - mp.getWidth()) {
                    x = getWidth() - mp.getWidth();
                    step = -step;
                } else if (x < 0) {
                    x = 0;
                    step = -step;
                }
                */
                //mp.setLocation(x, y);
            }
        });
        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
